### ISSUE TITLE
u_int32_t type not defined in C

### ISSUE THREAD

**Issue by raysan5** [dbriemann/libpartikel#1]
When compiling with C99 using MinGW GCC compiler, type is not recognized, it requires:
```c
#include <stdint.h>

typedef uint32_t u_int32_t;
```
Personally, I prefer to avoid non default language types...

**Comment by dbriemann** [comment]
I am used to this kind of descriptive types from other languages. But there is really no need to use it here.. especially since raylib doesn't use them and libpartikel is just some "addon" for raylib.

Changed it. Thx for your input
