### ISSUE TITLE
Header only library should follow stb libs convention

### ISSUE THREAD

**Issue by raysan5** [dbriemann/libpartikel#2]
When creating a single header library, it's recommended to follow stb library conventions, in case the same header needs to be included in multiple modules: https://github.com/nothings/stb/blob/master/docs/stb_howto.txt

Here some examples of single header libraries in raylib:
https://github.com/raysan5/raylib/blob/master/src/camera.h
https://github.com/raysan5/raylib/blob/master/src/gestures.h
https://github.com/raysan5/raylib/blob/master/src/raymath.h

**Comment by dbriemann** [comment]
Hi thanks for the input. I didn't know that.

I pushed a "fix" to the multiple include problem which should work. If you have time can you have a quick look at it?

Other criteria from stb_howto such as no dependencies etc. I ignored for now. It is intended to be used with raylib so the dependencies should be fine in my opinion.

**Comment by raysan5** [comment]
Hey @dbriemann, I'll take a look ASAP.

**Comment by dbriemann** [comment]
Nice. No hurries!
Also I just realized I have to ping you @raysan5 for a notice :)
