### ISSUE TITLE
Some functions already defined in raylib

### ISSUE THREAD

**Issue by raysan5** [dbriemann/libpartikel#3]
Hi @dbriemann, just noticed that some functions you use are already available in raylib, there is no need for redefinition... but you can if you want...
```c
float DegreesToRad(float deg);
float RadToDegrees(float rad);
```
raylib.h defines:
```c
#define DEG2RAD (PI/180.0f)
#define RAD2DEG (180.0f/PI)
```

Also noted that some includes are not necessary in the header part an cn be moved to implementation part of the code:
```c
#include "stdlib.h"     // Can be moved to implementation part
#include "stdbool.h"    // Not required, bool already defined/included in raylib.h
#include "math.h"       // Can be moved to implementation part
#include "raylib.h"
```

**Comment by dbriemann** [comment]
Hey @raysan5 thanks for your review!

I had to replace a size_t to move stdlib.h to implementation but that's ok. Fixed all the things you mentioned and pushed it.

 Good to know about DEG2RAD and RAD2DEG. Have you thought about adding a function to raylib that generates random (float or double) values between 0 and 1? I think it would be a useful addition.

**Comment by raysan5** [comment]
Yeah, I though about that but at the end I decided that the same could be archived with:
```c
int GetRandomValue(int min, int max); 
```
and just let the user define the decimal precission level:
```c
float value = (float)GetRandomValue(0, 1000)/1000.0f;  // Random between 0.000f and 1.000f
```
