### ISSUE TITLE
Particle editor tool (raygui based)

### ISSUE THREAD

**Issue by raysan5** [dbriemann/libpartikel#4]
Hi @dbriemann!

As you stated in the README, It would be GREAT a simple particle editor using [raygui](https://github.com/raysan5/raygui)!

Just note that, despite being functional, raygui is still a work in progress and some parts require some review... specially styling related parts.

You can also try [rGuiLayout](https://github.com/raysan5/raygui/tree/master/tools/rGuiLayout) tool, it's a work-in-progress tool to create GUI layouts with raygui and export them directly to code. Very prototype phase but functional...

I'll try to focus on raygui and tools for some days to improve usage...

**Comment by dbriemann** [comment]
I plan on using raygui definitively in the near future. However the particle editor will probably have to wait a bit because I want to be sure about the API of this library first. 

I will check out the rGuiLayout tool in time!
